@host=http://localhost:5221


POST {{host}}/auth/register
Content-Type: application/json

{
  "firstname": "Oluwatomi",
  "lastname": "Oluwatomi",
  "email": "Oluwatomi@gmail.com",
  "password": "Oluwatomi"
}